services:
  fiapcloudgames.api:
    image: ${DOCKER_REGISTRY-}fiapcloudgamesapi
    depends_on:
      - db
    build:
      context: .
      dockerfile: FiapCloudGames.API/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Adm1n23%"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: